### PR TITLE
Initialize k4abt_tracker_ after IMU is started.

### PR DESCRIPTION
**Pull request by zchenpds**
Sorry I did not see your reply before I took the liberty of fixing the object copying issue myself in the first one of the two commits. The second commit is aimed to fix the issue of function `k4abt_tracker_create` taking too long to finish and causing the warning
```
[ WARN] [1565983421.358836690]: Setting the time base using a k4a_image_t timestamp. This will result in a larger uncertainty than setting the time base using the timestamp of a k4a_imu_sample_t sample. Assuming the transmission delay to be 110 ms.
```

### Description of the changes:
- Create the body tracker after `startImu()` is called to obtain a better `start_time_`.

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [x] I tested my changes with a device

### I tested changes on: 
- [ ] Windows
- [x] Linux

### CODE REVIEW

**Review by RoseFlunder — COMMENTED** [review]
Do we really need the bool `is_k4abt_tracker_ready_`?
I'm currently not at home but I would guess the `k4abt_tracker_ ` would still be null  (as initialized in the constructor) if the creation fails. If so, we could just check if `k4abt_tracker_ ` evaluates to `true` instead of introducing the bool member.

According to the C-API reference the pointer given to `k4abt_tracker_create` will only point to an object on success:

https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/0.9.x/group__btfunctions_gae395d73880395ffc6ffbdd5132aa9181.html#gae395d73880395ffc6ffbdd5132aa9181
> Output parameter which on success will return a handle to the body tracker.

**Comment by RoseFlunder** [comment]
About the return const pointer vs return by value I don't really have a strong opinion.
I already wrote my thoughts about in the other repo but here again:

I see reason for both ways. By value is the safer choice to prevent manipulating the member variable (deleting it from the outside). Const pointer prevents one copy, but I don't really think that this copy is a big deal because its only called once and the value is also in a short lived scope so memory frees up after it. So I lean towards keeping it as a copy for the safe way but if you are a experienced c++ developer and tell me that its bad practice or costly to copy it, we can make your change to a const pointer.
I am still relatively new to the c++ world.

**Comment by zchenpds** [comment]
@RoseFlunder 
> Do we really need the bool is_k4abt_tracker_ready_?

I am afraid we do need something like `is_k4abt_tracker_ready_` because function `k4abt_tracker_enqueue_capture` is called in the child thread procedure `K4AROSDevice::framePublisherThread()` while `k4abt_tracker_create` is called in the main thread. The value of `k4abt_tracker_ ` could change to non-zero even before `k4abt_tracker_create` returns, hence we need something like `is_k4abt_tracker_ready_` to indicate whether `k4abt_tracker_create` has finished successfully. In case it is not finished yet and `k4abt_tracker_ ` becomes non-null, `k4abt_tracker_enqueue_capture` would throw an exception if called .

On the other hand, I am not sure if we need to set the values of `is_k4abt_tracker_ready_` and `k4abt_tracker_` to null inside `stopBodyTracker()`. In the current implementation, it is safe to call `stopBodyTracker()` in the destructor because the child threads are joined there before `stopBodyTracker()` is called, but potentially not safe in other places. What do you think?

> About the return const pointer vs return by value.

Thanks a lot for elaborating your thoughts. I agree that it is not a costly copy although I do not consider myself an experienced C++ developer. I will remove the first commit from this pull request later today.

**Comment by RoseFlunder** [comment]
Okay. I understand.
Maybe I got a solution to solve your problem with the start time and prevent introducing the bool.
How about moving the `k4a_device_.start_cameras(&k4a_configuration);` call after the body tracker was created successfully.
This would be just a very minor change to current codebase.

So the order is:
1. `calibration_data_.initialize` ...
2. create body tracker ...
3. start_cameras ...
4. start frame publisher thread

Once we got the calibration data ready, we can create the body tracker.
Once this is successfull we can start camera and then with very little delay imu gets started and the imu sample should be ready earlier than a camera capture.

**Comment by RoseFlunder** [comment]
The reason why i want the body tracker to be ready before the threads is that we will get the full body tracking data for all frames.
If we create it after the threads we miss some body tracking data from the first few frames.
Might not be that relevant in most live capture use cases, but in my other pull request I added a recording playback functionality and I would like a reproduceable behaviour of always getting the same amount of body tracking data messages each time the same recording is opened.
So the body tracker should be ready before the recording starts playing its captures (the threads get started).

**Comment by zchenpds** [comment]
Sounds like a much simpler solution to my problem! Do you want to make the changes on your end? If so, you could close this pull request. I should have created an issue before I tried to make my own changes LOL.

**Comment by RoseFlunder** [comment]
No problem, I appreciate that you look at my pull requests and try to improve the code.
I am in no way perfect and I am happy about proposals to improve the code.
Yes I can do a quick commit but you could test it afterwards too if everything works as expected for you.

**Comment by zchenpds** [comment]
Sounds great. I appreciate your fast response to my inquiry as well as your valuable contribution to this repo.

**Pull request closed without merging**
